import { UnitType, Hero } from "types";

const units: UnitType[] = [
  {
    water: 3,
    earth: 9,
    fire: 2,
    name: "Quellara Yaralune",
    level: 0,
    effect: {
      stage: "after",
      method: "debuffEnemy",
      methodArgs: { land: "water", value: 3 },
    },
    specialExplanation: "",
    image: "water-warrior-1.jpg",
    evolutions: [],
  },
  {
    water: 3,
    earth: 9,
    fire: 2,
    name: "Quellara Yaralune",
    level: 0,
    effect: {
      stage: "after",
      method: "debuffEnemy",
      methodArgs: { land: "water", value: 3 },
    },
    specialExplanation: "",
    image: "fire-mage-1.png",
    evolutions: [],
  },
  {
    water: 3,
    earth: 9,
    fire: 2,
    name: "Quellara Yaralune",
    level: 0,
    effect: {
      stage: "after",
      method: "debuffEnemy",
      methodArgs: { land: "water", value: 3 },
    },
    specialExplanation: "",
    image: "water-witch-1.jpg",
    evolutions: [],
  },
];
export const heroes: Hero[] = [
  {
    _id: "1",
    name: "Quellara Yaralune",
    type: {
      water: 3,
      earth: 9,
      fire: 2,
      wind: 0,
      slots: 3,
      image: "water-warrior-1.jpg",
      evolutions: [],
      level: 0,
      counterEspionageLevel: 0,
    },
    units,
    player: "1",
    x: 0,
    y: 0,
    alive: true,
    mission: null,
    level: 0,
    experienceTillLevelUp: 0,
  },
  {
    _id: "2",
    name: "Ivana Lunespear",
    type: {
      water: 3,
      earth: 9,
      fire: 2,
      wind: 0,
      slots: 3,
      image: "fire-warrior-1.jpg",
      evolutions: [],
      level: 0,
      counterEspionageLevel: 0,
    },
    units,
    player: "2",
    x: 0,
    y: 0,
    alive: true,
    mission: null,
    level: 0,
    experienceTillLevelUp: 0,
  },
  {
    _id: "3",
    name: "Donika Bivol",
    type: {
      water: 3,
      earth: 9,
      fire: 2,
      wind: 0,
      slots: 3,
      image: "earth-golem-2.jpg",
      evolutions: [],
      level: 0,
      counterEspionageLevel: 0,
    },
    units,
    player: "3",
    x: 0,
    y: 0,
    alive: true,
    mission: null,
    level: 0,
    experienceTillLevelUp: 0,
  },
];
