import { UnitType, Hero, HeroType } from "types";

const fireMageUnits: UnitType[] = [
  {
    water: 2,
    earth: 1,
    fire: 8,
    name: "Glowspire Vulcanis",
    level: 0,
    effect: {
      stage: "after",
      method: "epicBattle",
      methodArgs: { land: "active", value: 3 },
      explanation:
        "After the battle buffs your active stat by 3 if your army is smaller than the enemies",
    },
    specialExplanation: "",
    image: "fire/mage/16.jpeg",
    evolutions: [],
    race: {
      type: "fire",
      race: "mage",
      weights: { earth: 0.1, water: 0.05, fire: 0.5, special: 0.35 },
      names: [
        "Pyrothius",
        "Blazeweaver",
        "Cinderflare",
        "Drakefury",
        "Emberlyn",
        "Flamecaller",
        "Glowspire",
        "Heathenblaze",
        "Infernara",
        "Jetscar",
        "Kindlevoid",
        "Lavabrand",
        "Magmara",
        "Novaflare",
        "Obsidianflare",
        "Pyrelight",
        "Quickspark",
        "Radiantash",
        "Scorchveil",
        "Therion",
        "Umbraflame",
        "Vulcanis",
        "Wildspark",
        "Xantheros",
        "Yflareon",
        "Zephyrember",
        "Ashthorn",
        "Blazebinder",
        "Cindervane",
        "Duskspark",
      ],
      heroWeights: {
        water: 0,
        earth: 0,
        fire: 0.6,
        leadership: 0.1,
        wind: 0.2,
        counterEspionage: 0.1,
      },
      maxImages: 24,
    },
  },
  {
    water: 2,
    earth: 1,
    fire: 10,
    name: "Pyrelight Heathenblaze",
    level: 0,
    effect: {
      stage: "after",
      method: "epicBattle",
      methodArgs: { land: "earth", value: 7 },
      explanation:
        "After the battle buffs your earth stat by 7 if your army is smaller than the enemies",
    },
    specialExplanation: "",
    image: "fire/mage/18.jpeg",
    evolutions: [],
    race: {
      type: "fire",
      race: "mage",
      weights: { earth: 0.1, water: 0.05, fire: 0.5, special: 0.35 },
      names: [
        "Pyrothius",
        "Blazeweaver",
        "Cinderflare",
        "Drakefury",
        "Emberlyn",
        "Flamecaller",
        "Glowspire",
        "Heathenblaze",
        "Infernara",
        "Jetscar",
        "Kindlevoid",
        "Lavabrand",
        "Magmara",
        "Novaflare",
        "Obsidianflare",
        "Pyrelight",
        "Quickspark",
        "Radiantash",
        "Scorchveil",
        "Therion",
        "Umbraflame",
        "Vulcanis",
        "Wildspark",
        "Xantheros",
        "Yflareon",
        "Zephyrember",
        "Ashthorn",
        "Blazebinder",
        "Cindervane",
        "Duskspark",
      ],
      heroWeights: {
        water: 0,
        earth: 0,
        fire: 0.6,
        leadership: 0.1,
        wind: 0.2,
        counterEspionage: 0.1,
      },
      maxImages: 24,
    },
  },
  {
    water: 3,
    earth: 2,
    fire: 9,
    name: "Cinderflare Therion",
    level: 0,
    effect: {
      stage: "after",
      method: "buffMeEffect",
      methodArgs: { land: "fire", value: 1 },
      explanation: "After the battle buff your fire stat by 1",
    },
    specialExplanation: "",
    image: "fire/mage/11.jpeg",
    evolutions: [],
    race: {
      type: "fire",
      race: "mage",
      weights: { earth: 0.1, water: 0.05, fire: 0.5, special: 0.35 },
      names: [
        "Pyrothius",
        "Blazeweaver",
        "Cinderflare",
        "Drakefury",
        "Emberlyn",
        "Flamecaller",
        "Glowspire",
        "Heathenblaze",
        "Infernara",
        "Jetscar",
        "Kindlevoid",
        "Lavabrand",
        "Magmara",
        "Novaflare",
        "Obsidianflare",
        "Pyrelight",
        "Quickspark",
        "Radiantash",
        "Scorchveil",
        "Therion",
        "Umbraflame",
        "Vulcanis",
        "Wildspark",
        "Xantheros",
        "Yflareon",
        "Zephyrember",
        "Ashthorn",
        "Blazebinder",
        "Cindervane",
        "Duskspark",
      ],
      heroWeights: {
        water: 0,
        earth: 0,
        fire: 0.6,
        leadership: 0.1,
        wind: 0.2,
        counterEspionage: 0.1,
      },
      maxImages: 24,
    },
  },
];
const earthGolemUnits: UnitType[] = [
  {
    water: 12,
    earth: 4,
    fire: 4,
    name: "Orebound Jadefist",
    level: 0,
    effect: {
      stage: "after",
      method: "buffMeEffect",
      methodArgs: { land: "earth" },
      explanation: "After the battle buff your earth stat by undefined",
    },
    specialExplanation: "",
    image: "earth/golem/1.jpeg",
    evolutions: [],
    race: {
      type: "earth",
      race: "golem",
      weights: { earth: 0.6, water: 0.2, fire: 0.15, special: 0.05 },
      names: [
        "Terranthos",
        "Bouldergrim",
        "Cragvein",
        "Dustforge",
        "Earthenshard",
        "Fossilheart",
        "Graniteclaw",
        "Hollowstone",
        "Ironroot",
        "Jadefist",
        "Kragmire",
        "Loamspire",
        "Mossmantle",
        "Nethrock",
        "Orebound",
        "Pebblecore",
        "Quartzbreaker",
        "Rubblethorn",
        "Stonewarden",
        "Thaloss",
        "Umberfist",
        "Verdigris",
        "Woldstone",
        "Xerolith",
        "Yarrowspire",
        "Zirconclash",
        "Aridspire",
        "Basaltgrip",
        "Clayrend",
        "Dunewarden",
      ],
      heroWeights: {
        water: 0.1,
        earth: 0.5,
        fire: 0,
        leadership: 0.1,
        wind: 0.1,
        counterEspionage: 0.2,
      },
      maxImages: 24,
      possibleEffects: ["buffMe", "debuffActiveEffect", "defenderAdvantage"],
    },
  },
  {
    water: 12,
    earth: 4,
    fire: 3,
    name: "Yarrowspire Terranthos",
    level: 0,
    effect: {
      stage: "pre",
      method: "defenderAdvantage",
      methodArgs: {},
      explanation:
        "After the battle buffs your active stat by undefined if your are the defender",
    },
    specialExplanation: "",
    image: "earth/golem/12.jpeg",
    evolutions: [],
    race: {
      type: "earth",
      race: "golem",
      weights: { earth: 0.6, water: 0.2, fire: 0.15, special: 0.05 },
      names: [
        "Terranthos",
        "Bouldergrim",
        "Cragvein",
        "Dustforge",
        "Earthenshard",
        "Fossilheart",
        "Graniteclaw",
        "Hollowstone",
        "Ironroot",
        "Jadefist",
        "Kragmire",
        "Loamspire",
        "Mossmantle",
        "Nethrock",
        "Orebound",
        "Pebblecore",
        "Quartzbreaker",
        "Rubblethorn",
        "Stonewarden",
        "Thaloss",
        "Umberfist",
        "Verdigris",
        "Woldstone",
        "Xerolith",
        "Yarrowspire",
        "Zirconclash",
        "Aridspire",
        "Basaltgrip",
        "Clayrend",
        "Dunewarden",
      ],
      heroWeights: {
        water: 0.1,
        earth: 0.5,
        fire: 0,
        leadership: 0.1,
        wind: 0.1,
        counterEspionage: 0.2,
      },
      maxImages: 24,
      possibleEffects: ["buffMe", "debuffActiveEffect", "defenderAdvantage"],
    },
  },
  {
    water: 12,
    earth: 4,
    fire: 3,
    name: "Graniteclaw Mossmantle",
    level: 0,
    effect: {
      stage: "after",
      method: "debuffActiveEffect",
      methodArgs: {},
      explanation: "After the battle debuff the opponents active effect",
    },
    specialExplanation: "",
    image: "earth/golem/15.jpeg",
    evolutions: [],
    race: {
      type: "earth",
      race: "golem",
      weights: { earth: 0.6, water: 0.2, fire: 0.15, special: 0.05 },
      names: [
        "Terranthos",
        "Bouldergrim",
        "Cragvein",
        "Dustforge",
        "Earthenshard",
        "Fossilheart",
        "Graniteclaw",
        "Hollowstone",
        "Ironroot",
        "Jadefist",
        "Kragmire",
        "Loamspire",
        "Mossmantle",
        "Nethrock",
        "Orebound",
        "Pebblecore",
        "Quartzbreaker",
        "Rubblethorn",
        "Stonewarden",
        "Thaloss",
        "Umberfist",
        "Verdigris",
        "Woldstone",
        "Xerolith",
        "Yarrowspire",
        "Zirconclash",
        "Aridspire",
        "Basaltgrip",
        "Clayrend",
        "Dunewarden",
      ],
      heroWeights: {
        water: 0.1,
        earth: 0.5,
        fire: 0,
        leadership: 0.1,
        wind: 0.1,
        counterEspionage: 0.2,
      },
      maxImages: 24,
      possibleEffects: ["buffMe", "debuffActiveEffect", "defenderAdvantage"],
    },
  },
];
const waterWitchUnits: UnitType[] = [
  {
    water: 3,
    earth: 11,
    fire: 1,
    name: "Naiadra Naiadra",
    level: 0,
    effect: {
      stage: "pre",
      method: "buffMeEffect",
      methodArgs: { land: "water", value: 1 },
      explanation: "After the battle buff your water stat by 1",
    },
    specialExplanation: "",
    image: "water/witch/17.jpeg",
    evolutions: [],
    race: {
      type: "water",
      race: "witch",
      weights: { earth: 0.15, water: 0.5, fire: 0.05, special: 0.35 },
      heroWeights: {
        water: 0.5,
        earth: 0.1,
        fire: 0,
        leadership: 0.2,
        wind: 0.2,
        counterEspionage: 0.1,
      },
      names: [
        "Aquarina",
        "Brineveil",
        "Coralyn",
        "Dewshade",
        "Ebbra",
        "Frostara",
        "Glacielle",
        "Hydralis",
        "Icelily",
        "Jadecrest",
        "Koralith",
        "Lunara",
        "Mistwraith",
        "Naiadra",
        "Oceara",
        "Pearlspell",
        "Quellara",
        "Ripplewhisper",
        "Seafrost",
        "Tidebinder",
        "Undinara",
        "Vaporlyn",
        "Wavecrest",
        "Xanthea",
        "Yaralune",
        "Zephyra",
        "Abyssara",
        "Brinewhisper",
        "Coralbreeze",
        "Dewspell",
      ],
      maxImages: 25,
      possibleEffects: [
        "removeEnemyEffectEffect",
        "buffActiveEffect",
        "buffMe",
        "debuffEnemyEffect",
        "defenderAdvantage",
        "attackerAdvantage",
      ],
    },
  },
  {
    water: 2,
    earth: 10,
    fire: 1,
    name: "Pearlspell Jadecrest",
    level: 0,
    effect: {
      stage: "pre",
      method: "attackerAdvantage",
      methodArgs: { value: 1 },
      explanation:
        "After the battle buffs your active effect by 1 if your are the attacker",
    },
    specialExplanation: "",
    image: "water/witch/7.jpeg",
    evolutions: [],
    race: {
      type: "water",
      race: "witch",
      weights: { earth: 0.15, water: 0.5, fire: 0.05, special: 0.35 },
      heroWeights: {
        water: 0.5,
        earth: 0.1,
        fire: 0,
        leadership: 0.2,
        wind: 0.2,
        counterEspionage: 0.1,
      },
      names: [
        "Aquarina",
        "Brineveil",
        "Coralyn",
        "Dewshade",
        "Ebbra",
        "Frostara",
        "Glacielle",
        "Hydralis",
        "Icelily",
        "Jadecrest",
        "Koralith",
        "Lunara",
        "Mistwraith",
        "Naiadra",
        "Oceara",
        "Pearlspell",
        "Quellara",
        "Ripplewhisper",
        "Seafrost",
        "Tidebinder",
        "Undinara",
        "Vaporlyn",
        "Wavecrest",
        "Xanthea",
        "Yaralune",
        "Zephyra",
        "Abyssara",
        "Brinewhisper",
        "Coralbreeze",
        "Dewspell",
      ],
      maxImages: 25,
      possibleEffects: [
        "removeEnemyEffectEffect",
        "buffActiveEffect",
        "buffMe",
        "debuffEnemyEffect",
        "defenderAdvantage",
        "attackerAdvantage",
      ],
    },
  },
  {
    water: 4,
    earth: 9,
    fire: 2,
    name: "Quellara Xanthea",
    level: 0,
    effect: {
      stage: "pre",
      method: "removeEnemyEffectEffect",
      methodArgs: {},
      explanation: "After the battle remove the opponents special effect",
    },
    specialExplanation: "",
    image: "water/witch/19.jpeg",
    evolutions: [],
    race: {
      type: "water",
      race: "witch",
      weights: { earth: 0.15, water: 0.5, fire: 0.05, special: 0.35 },
      heroWeights: {
        water: 0.5,
        earth: 0.1,
        fire: 0,
        leadership: 0.2,
        wind: 0.2,
        counterEspionage: 0.1,
      },
      names: [
        "Aquarina",
        "Brineveil",
        "Coralyn",
        "Dewshade",
        "Ebbra",
        "Frostara",
        "Glacielle",
        "Hydralis",
        "Icelily",
        "Jadecrest",
        "Koralith",
        "Lunara",
        "Mistwraith",
        "Naiadra",
        "Oceara",
        "Pearlspell",
        "Quellara",
        "Ripplewhisper",
        "Seafrost",
        "Tidebinder",
        "Undinara",
        "Vaporlyn",
        "Wavecrest",
        "Xanthea",
        "Yaralune",
        "Zephyra",
        "Abyssara",
        "Brinewhisper",
        "Coralbreeze",
        "Dewspell",
      ],
      maxImages: 25,
      possibleEffects: [
        "removeEnemyEffectEffect",
        "buffActiveEffect",
        "buffMe",
        "debuffEnemyEffect",
        "defenderAdvantage",
        "attackerAdvantage",
      ],
    },
  },
];
export const predefinedHeroTypes: (HeroType & { units: UnitType[] })[] = [
  {
    water: 5,
    earth: 3,
    fire: 3,
    leadership: 3,
    wind: 3,
    counterEspionage: 3,
    name: "Radiantash Therion",
    evolutions: [],
    howManyPeopleHaveIt: 0,
    image: "fire/mage/17.jpeg",
    units: fireMageUnits,
    level: 0,
    race: {
      type: "fire",
      race: "mage",
      weights: { earth: 0.1, water: 0.05, fire: 0.5, special: 0.35 },
      names: [
        "Pyrothius",
        "Blazeweaver",
        "Cinderflare",
        "Drakefury",
        "Emberlyn",
        "Flamecaller",
        "Glowspire",
        "Heathenblaze",
        "Infernara",
        "Jetscar",
        "Kindlevoid",
        "Lavabrand",
        "Magmara",
        "Novaflare",
        "Obsidianflare",
        "Pyrelight",
        "Quickspark",
        "Radiantash",
        "Scorchveil",
        "Therion",
        "Umbraflame",
        "Vulcanis",
        "Wildspark",
        "Xantheros",
        "Yflareon",
        "Zephyrember",
        "Ashthorn",
        "Blazebinder",
        "Cindervane",
        "Duskspark",
      ],
      heroWeights: {
        water: 0,
        earth: 0,
        fire: 0.6,
        leadership: 0.1,
        wind: 0.2,
        counterEspionage: 0.1,
      },
      maxImages: 24,
    },
  },
  {
    water: 4,
    earth: 3,
    fire: 3,
    leadership: 3,
    wind: 3,
    counterEspionage: 4,
    name: "Bouldergrim Nethrock",
    evolutions: [],
    units: earthGolemUnits,
    howManyPeopleHaveIt: 0,
    image: "earth/golem/19.jpeg",
    level: 0,
    race: {
      type: "earth",
      race: "golem",
      weights: { earth: 0.6, water: 0.2, fire: 0.15, special: 0.05 },
      names: [
        "Terranthos",
        "Bouldergrim",
        "Cragvein",
        "Dustforge",
        "Earthenshard",
        "Fossilheart",
        "Graniteclaw",
        "Hollowstone",
        "Ironroot",
        "Jadefist",
        "Kragmire",
        "Loamspire",
        "Mossmantle",
        "Nethrock",
        "Orebound",
        "Pebblecore",
        "Quartzbreaker",
        "Rubblethorn",
        "Stonewarden",
        "Thaloss",
        "Umberfist",
        "Verdigris",
        "Woldstone",
        "Xerolith",
        "Yarrowspire",
        "Zirconclash",
        "Aridspire",
        "Basaltgrip",
        "Clayrend",
        "Dunewarden",
      ],
      heroWeights: {
        water: 0.1,
        earth: 0.5,
        fire: 0,
        leadership: 0.1,
        wind: 0.1,
        counterEspionage: 0.2,
      },
      maxImages: 24,
      possibleEffects: ["buffMe", "debuffActiveEffect", "defenderAdvantage"],
    },
  },
  {
    water: 5,
    earth: 3,
    fire: 3,
    leadership: 3,
    wind: 3,
    counterEspionage: 3,
    name: "Xanthea Frostara",
    evolutions: [],
    units: waterWitchUnits,
    howManyPeopleHaveIt: 0,
    image: "water/witch/19.jpeg",
    level: 0,
    race: {
      type: "water",
      race: "witch",
      weights: { earth: 0.15, water: 0.5, fire: 0.05, special: 0.35 },
      heroWeights: {
        water: 0.5,
        earth: 0.1,
        fire: 0,
        leadership: 0.2,
        wind: 0.2,
        counterEspionage: 0.1,
      },
      names: [
        "Aquarina",
        "Brineveil",
        "Coralyn",
        "Dewshade",
        "Ebbra",
        "Frostara",
        "Glacielle",
        "Hydralis",
        "Icelily",
        "Jadecrest",
        "Koralith",
        "Lunara",
        "Mistwraith",
        "Naiadra",
        "Oceara",
        "Pearlspell",
        "Quellara",
        "Ripplewhisper",
        "Seafrost",
        "Tidebinder",
        "Undinara",
        "Vaporlyn",
        "Wavecrest",
        "Xanthea",
        "Yaralune",
        "Zephyra",
        "Abyssara",
        "Brinewhisper",
        "Coralbreeze",
        "Dewspell",
      ],
      maxImages: 25,
      possibleEffects: [
        "removeEnemyEffectEffect",
        "buffActiveEffect",
        "buffMe",
        "debuffEnemyEffect",
        "defenderAdvantage",
        "attackerAdvantage",
      ],
    },
  },
];
