import { UnitType, Hero, HeroType, Unit } from "types";

// First, let's define the unit types
const earthbrandJadefistType: UnitType = {
  water: 1,
  earth: 1,
  fire: 1,
  name: "Earthbrand Jadefist",
  level: 0,
  effect: {
    stage: "after",
    method: "buffMeEffect",
    methodArgs: { land: "earth", value: 1 },
    explanation: "After the battle buff your earth stat by 1",
  },
  specialExplanation: "",
  image: "earth/golem/12.jpeg",
  evolutions: [],
  race: {
    type: "earth",
    race: "golem",
    weights: { earth: 0.6, water: 0.2, fire: 0.15, special: 0.05 },
    names: [
      "Terranthos",
      "Bouldergrim",
      "Cragvein",
      "Dustforge",
      "Earthenshard",
      "Fossilheart",
      "Graniteclaw",
      "Hollowstone",
      "Ironroot",
      "Jadefist",
      "Kragmire",
      "Loamspire",
      "Mossmantle",
      "Nethrock",
      "Orebound",
      "Pebblecore",
      "Quartzbreaker",
      "Rubblethorn",
      "Stonewarden",
      "Thaloss",
      "Umberfist",
      "Verdigris",
      "Woldstone",
      "Xerolith",
      "Yarrowspire",
      "Zirconclash",
      "Aridspire",
      "Basaltgrip",
      "Clayrend",
      "Dunewarden",
    ],
    heroWeights: {
      water: 0.1,
      earth: 0.5,
      fire: 0,
      leadership: 0.1,
      wind: 0.1,
      counterEspionage: 0.2,
    },
    maxImages: 24,
    possibleEffects: ["buffMe", "debuffActiveEffect", "defenderAdvantage"],
  },
};

const damionLightType: UnitType = {
  water: 2,
  earth: 1,
  fire: 1,
  name: "Damion Light",
  level: 0,
  effect: {
    stage: "after",
    method: "epicBattle",
    methodArgs: { land: "earth", value: 1 },
    explanation:
      "After the battle buffs your earth stat by 1 if your army is smaller than the enemies",
  },
  specialExplanation: "",
  image: "fire/mage/18.jpeg",
  evolutions: [],
  race: {
    type: "fire",
    race: "mage",
    weights: { earth: 0.1, water: 0.05, fire: 0.5, special: 0.35 },
    names: [
      "Pyrothius",
      "Blazeweaver",
      "Cinderflare",
      "Drakefury",
      "Emberlyn",
      "Flamecaller",
      "Glowspire",
      "Heathenblaze",
      "Infernara",
      "Jetscar",
      "Kindlevoid",
      "Lavabrand",
      "Magmara",
      "Novaflare",
      "Obsidianflare",
      "Pyrelight",
      "Quickspark",
      "Radiantash",
      "Scorchveil",
      "Therion",
      "Umbraflame",
      "Vulcanis",
      "Wildspark",
      "Xantheros",
      "Yflareon",
      "Zephyrember",
      "Ashthorn",
      "Blazebinder",
      "Cindervane",
      "Duskspark",
    ],
    heroWeights: {
      water: 0,
      earth: 0,
      fire: 0.6,
      leadership: 0.1,
      wind: 0.2,
      counterEspionage: 0.1,
    },
    maxImages: 24,
  },
};

const aquariusEquinumType: UnitType = {
  water: 2,
  earth: 2,
  fire: 1,
  name: "Aquarius Equinum",
  level: 0,
  effect: {
    stage: "pre",
    method: "attackerAdvantage",
    methodArgs: { value: 1 },
    explanation:
      "After the battle buffs your active effect by 1 if your are the attacker",
  },
  specialExplanation: "",
  image: "water/witch/7.jpeg",
  evolutions: [],
  race: {
    type: "water",
    race: "witch",
    weights: { earth: 0.15, water: 0.5, fire: 0.05, special: 0.35 },
    heroWeights: {
      water: 0.5,
      earth: 0.1,
      fire: 0,
      leadership: 0.2,
      wind: 0.2,
      counterEspionage: 0.1,
    },
    names: [
      "Aquarina",
      "Brineveil",
      "Coralyn",
      "Dewshade",
      "Ebbra",
      "Frostara",
      "Glacielle",
      "Hydralis",
      "Icelily",
      "Jadecrest",
      "Koralith",
      "Lunara",
      "Mistwraith",
      "Naiadra",
      "Oceara",
      "Pearlspell",
      "Quellara",
      "Ripplewhisper",
      "Seafrost",
      "Tidebinder",
      "Undinara",
      "Vaporlyn",
      "Wavecrest",
      "Xanthea",
      "Yaralune",
      "Zephyra",
      "Abyssara",
      "Brinewhisper",
      "Coralbreeze",
      "Dewspell",
    ],
    maxImages: 25,
    possibleEffects: [
      "removeEnemyEffectEffect",
      "buffActiveEffect",
      "buffMe",
      "debuffEnemyEffect",
      "defenderAdvantage",
      "attackerAdvantage",
    ],
  },
};

// Now create the Unit objects with their types
export const neutralUnits: Unit[] = [
  {
    _id: "neutral-earthbrand-jadefist",
    type: earthbrandJadefistType,
    holder: null as any, // This will be set when the unit is assigned
    experienceTillLevelUp: 100,
  },
  {
    _id: "neutral-damion-light",
    type: damionLightType,
    holder: null as any, // This will be set when the unit is assigned
    experienceTillLevelUp: 100,
  },
  {
    _id: "neutral-aquarius-equinum",
    type: aquariusEquinumType,
    holder: null as any, // This will be set when the unit is assigned
    experienceTillLevelUp: 100,
  },
];

export const predefinedNeutrals: HeroType & { units: Unit[] } = {
  water: 2,
  earth: 1,
  fire: 1,
  leadership: 3,
  wind: 3,
  counterEspionage: 3,
  name: "Darko Lidgin",
  evolutions: [],
  howManyPeopleHaveIt: 0,
  image: "fire/mage/6.jpeg",
  units: neutralUnits,
  level: 0,
  race: {
    type: "fire",
    race: "mage",
    weights: { earth: 0.1, water: 0.05, fire: 0.5, special: 0.35 },
    names: [
      "Pyrothius",
      "Blazeweaver",
      "Cinderflare",
      "Drakefury",
      "Emberlyn",
      "Flamecaller",
      "Glowspire",
      "Heathenblaze",
      "Infernara",
      "Jetscar",
      "Kindlevoid",
      "Lavabrand",
      "Magmara",
      "Novaflare",
      "Obsidianflare",
      "Pyrelight",
      "Quickspark",
      "Radiantash",
      "Scorchveil",
      "Therion",
      "Umbraflame",
      "Vulcanis",
      "Wildspark",
      "Xantheros",
      "Yflareon",
      "Zephyrember",
      "Ashthorn",
      "Blazebinder",
      "Cindervane",
      "Duskspark",
    ],
    heroWeights: {
      water: 0,
      earth: 0,
      fire: 0.6,
      leadership: 0.1,
      wind: 0.2,
      counterEspionage: 0.1,
    },
    maxImages: 24,
  },
};
